version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    target-branch: "main"
    open-pull-requests-limit: 50
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Asia/Shanghai"
