stages:
  - pages

pages:
  stage: pages
  image: node:20.12.0
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - node_modules/
  script:
    - npm run pre:npm
    - if [ $CI_SERVER_HOST == 'framagit.org' ]; then
      cat .vitepress/config.mts;
      sed -i 's#在 Gitee 上编辑此页面#在 FramaGit 上编辑#g' .vitepress/config.mts;
      sed -i 's#https://gitee.com/xuxiaowei-com-cn/xuxiaowei-com-cn/edit/docs/#https://framagit.org/xuxiaowei-com-cn/xuxiaowei-com-cn.frama.io/-/edit/docs/#g' .vitepress/config.mts;
      sed -i 's#<a id="beian-miit-gov-cn" target="_blank" href="https://beian.miit.gov.cn">鲁ICP备19009036号-1</a>##g' .vitepress/config.mts;
      cat .vitepress/config.mts;
      fi
    - npm run docs:build
    - mv .vitepress/dist/* public/
  artifacts:
    expire_in: 1 week
    paths:
      - public/
  rules:
    - if: $ENABLE_DOCS == "true"
