services:
  xuxiaowei-com-cn-docs:
    image: registry.cn-qingdao.aliyuncs.com/xuxiaoweicomcn/xuxiaowei-com-cn-docs:${DOCKER_TAG}-${CI_PIPELINE_ID}
    restart: always
    ports:
      - ${XUXIAOWEI_COM_CN_DOCS_PORT:-45950}:80
    volumes:
      - /xuxiaowei-com-cn-docs/logs:/var/log/nginx
    container_name: xuxiaowei-com-cn-docs
